#! /bin/sh

BASEDIR=/var/beListful
 
case "$1" in
  start)
    node $BASEDIR/src/beListful.js start > /var/log/beListful.log 2> /var/log/beListful.err
    ;;
  stop)
    node $BASEDIR/src/beListful.js stop
    ;;
  restart)
    node $BASEDIR/src/beListful.js stop
    node $BASEDIR/src/beListful.js start > /var/log/beListful.log 2> /var/log/beListful.err
    ;;
 
  force-reload)
    # No-op
    ;;
  *)
    echo "Usage: beListful-httpd {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac
 
:
